---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    prometheus: monitored
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: mongodb-exporter