{
 "title": "MongoDB Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(mongodb_connections, instance)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "service", "query": "mongodb-exporter" },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(mongodb_top_commands_count{service=~\"$service\"}, database)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Latency and Operations Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Operation Rate",
   "type": "timeseries",
   "description": "Tasa de operaciones por tipo en MongoDB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_ops_total[$interval])",
     "legendFormat": "{{type}} Operations"
    }
   ]
  },
  {
   "title": "MongoDB Operation Latency",
   "type": "timeseries",
   "description": "Latencia promedio por tipo de operación en MongoDB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(mongodb_mongod_op_latencies_latency_total) by (type) / sum(mongodb_mongod_op_latencies_ops_total) by (type)",
     "legendFormat": "{{type}} Latency"
    }
   ]
  },
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "description": "Este panel muestra la tasa de operaciones en MongoDB, medida a través de la métrica op_counters_total. Se calcula para las instancias que coinciden con el entorno seleccionado ($env) en un intervalo de tiempo configurable ($interval). La métrica abarca las operaciones totales realizadas en la base de datos, proporcionando información clave para evaluar la carga y el rendimiento de las operaciones de MongoDB.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "Esta métrica mide la tasa de operaciones relacionadas con documentos realizadas por MongoDB en un intervalo de tiempo especificado.",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "timeseries",
   "description": "Este panel muestra la tasa de ejecución de consultas en MongoDB, basada en la métrica query_executor_total. El cálculo se realiza para las instancias que coinciden con el entorno seleccionado ($env) en un intervalo de tiempo configurable ($interval). Esta métrica es útil para monitorear la actividad de las consultas ejecutadas en la base de datos y detectar patrones de carga o posibles problemas de rendimiento.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Replica Set Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "env" },
  {
   "title": "Member Health",
   "type": "graph",
   "description": "Esta métrica muestra el número de miembros en el conjunto de réplicas de MongoDB, medida a través de la métrica mongodb_mongod_replset_number_of_members. La primera consulta obtiene el número de miembros por cada instancia en el entorno seleccionado ($env), mientras que la segunda consulta suma el número total de miembros en todas las instancias seleccionadas, en un intervalo de tiempo configurable ($interval). Esta métrica es útil para monitorear la salud y la configuración de los miembros en el conjunto de réplicas de MongoDB.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=~\"$env\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_mongod_replset_number_of_members{instance=~\"$env\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "graph",
   "description": "Esta métrica muestra el estado del último latido (heartbeat) de los miembros en el conjunto de réplicas de MongoDB, a través de la métrica mongodb_mongod_replset_member_last_heartbeat. Se calcula para las instancias que coinciden con el entorno seleccionado ($env). Esta métrica es útil para monitorear la conectividad y la sincronización de los miembros del conjunto de réplicas, ayudando a detectar posibles fallos o retrasos en la comunicación.",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_last_heartbeat{instance=~\"$env\"}",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "timeseries",
   "description": "Esta métrica muestra la tasa de operaciones de réplica en MongoDB, basada en la métrica mongodb_mongod_op_counters_repl_total. Se calcula para las instancias que coinciden con el entorno seleccionado ($env) en un intervalo de tiempo configurable ($interval). Esta métrica es útil para monitorear las operaciones realizadas por el proceso de réplica en MongoDB, proporcionando información sobre la carga y el rendimiento del sistema en operaciones de replicación.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Health metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Esta métrica muestra el tiempo de actividad (uptime) de la instancia de MongoDB, medido en segundos a través de la métrica mongodb_instance_uptime_seconds. Se calcula para las instancias que coinciden con el entorno seleccionado ($env). Esta métrica es útil para monitorear el tiempo que ha estado funcionando una instancia de MongoDB sin interrupciones, lo cual es importante para evaluar la estabilidad del sistema.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=~\"$env\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "description": "Esta métrica muestra el número de conexiones disponibles en MongoDB, basada en la métrica mongodb_connections con el estado available. Se calcula para las instancias que coinciden con el entorno seleccionado ($env). Esta métrica es útil para monitorear la cantidad de conexiones disponibles para nuevos clientes, lo que permite evaluar la capacidad del sistema para manejar solicitudes de conexión sin que se produzcan cuellos de botella.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$env\",state=\"available\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "description": "Esta métrica muestra el número de conexiones abiertas actualmente en MongoDB, medida a través de la métrica mongodb_ss_connections con el estado current. Se calcula para las instancias que coinciden con el entorno seleccionado ($env). Esta métrica es útil para monitorear la cantidad de conexiones activas en el sistema, lo que ayuda a evaluar la carga actual en MongoDB y detectar posibles problemas de rendimiento o saturación de conexiones.",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{instance=~\"$env\",conn_type=\"current\"}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Esta métrica muestra el uso de memoria en MongoDB, medida a través de la métrica mongodb_memory para los tipos de memoria resident y virtual. Se calcula para las instancias que coinciden con el entorno seleccionado ($env). La memoria \"resident\" refleja la cantidad de memoria física utilizada por MongoDB, mientras que la memoria \"virtual\" muestra la memoria total, incluyendo la paginada. Esta métrica es útil para monitorear el uso de memoria y evaluar la eficiencia del sistema en cuanto al manejo de recursos.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$env\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Esta métrica muestra la tasa de tráfico de red en MongoDB, combinando los bytes enviados (mongodb_ss_network_bytesOut) y los bytes recibidos (mongodb_ss_network_bytesIn). Se calcula para las instancias que coinciden con el entorno seleccionado ($env) en un intervalo de tiempo configurable ($interval). La suma de ambas métricas proporciona una visión completa del flujo de datos hacia y desde MongoDB, permitiendo monitorear el rendimiento de la red y detectar posibles cuellos de botella o problemas de comunicación.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesOut[$interval])",
     "legendFormat": "Salida (MB/s)"
    },
    {
     "expr": "rate(mongodb_ss_network_bytesIn[$interval])",
     "legendFormat": "Entrada (MB/s)"
    },
    {
     "expr": "(rate(mongodb_ss_network_bytesOut[$interval]) + rate(mongodb_ss_network_bytesIn[$interval]))",
     "legendFormat": "Total (MB/s)"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Oplog Lag",
   "type": "timeseries",
   "description": "Esta métrica muestra la tasa de retraso (lag) del registro de operaciones (oplog) en MongoDB, medida a través de la métrica mongodb_mongod_replset_oplog_head_timestamp. Se calcula para las instancias que coinciden con el entorno seleccionado ($env) en un intervalo de 5 minutos (5m). Esta métrica es útil para monitorear el retraso en la replicación entre el primario y los secundarios de un conjunto de réplicas, proporcionando una visión del tiempo que ha transcurrido desde la última operación registrada en el oplog. Un alto valor de lag puede indicar problemas en la sincronización entre los nodos del conjunto de réplicas.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_replset_oplog_head_timestamp[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Database Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Collections statistics  for $database (summary)",
   "type": "timeseries",
   "description": "Proporciona información resumida sobre la actividad que se ejecuta en la base de datos y luego se desglosa en tipos de actividad durante el período de tiempo seleccionado.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_commands_count {database=~\"$database\",service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Commands - {{database}}"
    },
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_insert_count {database=~\"$database\",service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Insert - {{database}}"
    },
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_update_count {database=~\"$database\",service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Update - {{database}}"
    },
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_remove_count{database=~\"$database\",service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Remove - {{database}}"
    },
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_getmore_count{database=~\"$database\",service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Getmore - {{database}}"
    }
   ]
  },
  {
   "title": "Collections statistics  for $database (rate)",
   "type": "timeseries",
   "description": "Proporciona información sobre la tasa de actividad en comparación con la base de datos y luego se desglosa en tipos de actividad durante el período de tiempo seleccionado.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (\n  rate(mongodb_top_commands_count{database=~\"$database\", service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Commands - {{database}}"
    },
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_insert_count {database=~\"$database\",service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Insert - {{database}}"
    },
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_update_count {database=~\"$database\", service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Update - {{database}}"
    },
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_remove_count {database=~\"$database\", service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Remove - {{database}}"
    },
    {
     "expr": "sum by (database) (\n    rate(mongodb_top_getmore_count {database=~\"$database\",service=~\"$service\"}[$interval])\n)",
     "legendFormat": "Getmore - {{database}}"
    }
   ]
  },
  {
   "title": "Collections statistics  $database",
   "type": "table",
   "description": "Proporciona totales para cada tipo de actividad que llega a una base de datos para colecciones.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "repeat": "database",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (collection) (mongodb_top_queries_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_insert_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_remove_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_update_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_getmore_count {database=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Size for Database ($database)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mongodb_dbstats_dataSize{database=~\"$database\",service=~\"$service\"})",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Collections in Database ($database)",
     "type": "stat",
     "description": "Proporciona el número de colecciones en las bases de datos seleccionadas.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(mongodb_top_commands_time{database=~\"$database\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "Index Size in Database ($database)",
     "type": "timeseries",
     "description": "Tamaño total de todos los índices en una base de datos determinada",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mongodb_dbstats_indexSize{database=~\"$database\", service=~\"$service\"})",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Indexes in Database ($database)",
     "type": "stat",
     "description": "Proporciona el número de índices en las bases de datos seleccionadas.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mongodb_dbstats_indexes{database=~\"$database\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "Avg Object Size in Database ($database)",
     "type": "timeseries",
     "description": "Tamaño medio de cada documento en bytes. tamaño de datos dividido por el número de documentos",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(mongodb_dbstats_avgObjSize{service=~\"$service\", database=~\"$database\"})",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Top 5 Databases By Size",
     "type": "timeseries",
     "description": "Proporciona los nombres y tamaños de las 5 bases de datos más grandes en una instancia/clúster. Los datos se muestran solo desde el nodo principal en el conjunto de réplicas.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "avg by (database) (topk(5, mongodb_dbstats_dataSize{rs_state=\"1\"})/1024/1024)",
       "legendFormat": "{{database}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Hottest Collections by Read  (Total)",
     "type": "table",
     "description": "Muestra información resumida sobre las 5 colecciones principales que se leen con más frecuencia.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "topk (5,sum by (database, collection) (mongodb_top_queries_count{database =~\"$database\",service=~\"$service\"}))"
      }
     ]
    },
    {
     "title": "Top 5 Hottest Collections by Write (Total)",
     "type": "table",
     "description": "Muestre información resumida sobre las 5 colecciones principales en las que se escribe con más frecuencia (insertar, actualizar, eliminar, etc.).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "topk(5,sum by (database,collection) (mongodb_top_insert_count{database=~\"$database\",service=~\"$service\"}) + sum by (database,collection) (mongodb_top_insert_count{database =~\"$database\",service=~\"$service\"}) + sum by (database,collection) (mongodb_top_remove_count{database =~\"$database\", service=~\"$service\"})+sum by (database,collection) (mongodb_top_update_count{database=~\"$database\", service=~\"$service\"}))"
      }
     ]
    },
    {
     "title": "Top 5 Hottest Collections by Read (Rate)",
     "type": "bargauge",
     "description": "Muestra las 5 colecciones que se leen con más frecuencia.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, \n  rate(mongodb_top_queries_count{database =~\"$database\", service=~\"$service\"}[$interval])\n)",
       "legendFormat": "{{ database }}.{{ collection }}"
      }
     ]
    },
    {
     "title": "Top 5 Hottest Collections by Write (Rate)",
     "type": "bargauge",
     "description": "Muestra las 5 colecciones en las que se escribe con más frecuencia (insertar, actualizar, eliminar, etc.).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, \n  sum by (environment, cluster, database, collection) (\n    rate(mongodb_top_insert_count{database =~\"$database\", service=~\"$service\"}[$interval]) +\n    rate(mongodb_top_insert_count{database =~\"$database\", service=~\"$service\"}[$interval]) +\n    rate(mongodb_top_remove_count{database =~\"$database\", service=~\"$service\"}[$interval]) +\n    rate(mongodb_top_update_count{database =~\"$database\", service=~\"$service\"}[$interval])\n  )\n)",
       "legendFormat": "{{ database }}.{{ collection }}"
      }
     ]
    }
   ]
  }
 ]
}