apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-processing-audio
  labels:
    app: backend-processing-audio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-processing-audio
  template:
    metadata:
      labels:
        app: backend-processing-audio
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.28
        command: ['sh', '-c', '
          until nc -z mongodb-service-cluster 27017; 
          do 
            echo waiting for mongodb;
            sleep 2; 
          done;']
      - name: wait-for-kafka
        image: busybox:1.28
        command: ['sh', '-c', '
          until nc -z kafka-headless 29092; 
          do 
            echo waiting for kafka;
            sleep 2; 
          done;']
      - name: wait-for-zookeeper
        image: busybox:1.28
        command: ['sh', '-c', '
          until nc -z zookeeper-headless 2181; 
          do 
            echo waiting for zookeeper;
            sleep 2; 
          done;']
      containers:
      - name: backend-processing-audio
        image: tomasvilte/music-downloader-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GIN_MODE
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_PORT
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_DATABASE
        - name: MONGO_COLLECTION_SONGS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_COLLECTION_SONGS
        - name: MONGO_COLLECTION_OPERATIONS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_COLLECTION_OPERATIONS
        - name: KAFKA_BROKERS
          value: "kafka-headless:29092"
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_TOPIC
        - name: LOCAL_STORAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOCAL_STORAGE_PATH
        - name: MONGO_USER 
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_PASSWORD
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: YOUTUBE_API_KEY
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_HOST
        volumeMounts:
        - name: yt-cookies-volume
          mountPath: /root/configurations/yt-cookies.txt
          subPath: yt-cookies.txt
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: yt-cookies-volume
        secret:
          secretName: backend-secret
          items:
          - key: YT_COOKIES
            path: yt-cookies.txt