---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: default
  namespace: monitoring
spec:
  replicas: 1
  version: v2.32.1
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: default
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534 
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi