---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    monitoring: prometheus
spec:
  endpoints:
  - port: web
  selector:
    matchLabels:
      operated-prometheus: "true"