---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    name: cadvisor
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: metrics
  selector:
    name: cadvisor