apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
  MONGO_USER: "root"
  MONGO_PASSWORD: "root"
  YT_COOKIES: "${YT_COOKIES}"