apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: kafka
spec:
  containers:
  - name: kafka-client
    image: quay.io/strimzi/kafka:0.44.0-kafka-3.8.0
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
    env:
    - name: KAFKA_OPTS
      value: "-Xmx512M -client"
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
