apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-ca
  namespace: kafka
spec:
  isCA: true
  commonName: kafka-ca
  secretName: kafka-ca-tls
  issuerRef:
    name: kafka-ca-issuer
    kind: Issuer