FROM --platform=linux/arm64 arm64v8/golang:1.21-alpine3.18 AS builder

# Instalar dependencias necesarias
RUN apk add --no-cache build-base opus-dev opusfile-dev \
    && go install github.com/bwmarrin/dca/cmd/dca@latest

WORKDIR /src/
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ cmd/
COPY internal/ internal/
RUN CGO_ENABLED=1 GOARCH=arm64 go build -ldflags="-s -w" -o /bin/butakero cmd/main.go

# Etapa final del contenedor
FROM --platform=linux/arm64 arm64v8/alpine:edge

ENV BUCKET_NAME=
ENV ACCESS_KEY=
ENV SECRET_KEY=
ENV REGION=
ENV KEY=
ENV INPUT_FILE_FROM_S3=
# Instalar dependencias necesarias para la ejecución
RUN apk add --no-cache ffmpeg

# Copiar los binarios compilados desde la etapa de construcción
COPY --from=builder /bin/butakero /bin/butakero
COPY --from=builder /go/bin/dca /usr/local/bin/dca

CMD ["/bin/butakero"]