apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Secrets
  - secrets/mongodb-secret.yaml
  - secrets/backend-secret.yaml

  # Stateful Services
  - stateful/zookeeper/service.yaml
  - stateful/zookeeper/statefulset.yaml
  - stateful/kafka/service.yaml
  - stateful/kafka/statefulset.yaml
  - stateful/mongodb/mongo-persistentvolume.yaml
  - stateful/mongodb/service.yaml
  - stateful/mongodb/mongo-configmap.yaml
  - stateful/mongodb/statefulset.yaml


  # Backend services
  - backend/configmap.yaml
  - backend/service.yaml
  - backend/deployment.yaml
