{
 "title": "Metricas del Bot de Discord",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(go_goroutines, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"bot:8080\", job=\"butakero-bot\"}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=\"bot:8080\", job=\"butakero-bot\"} - go_memstats_other_sys_bytes{instance=\"172.17.0.1:8080\", job=\"butakero-bot\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    }
   ]
  },
  {
   "title": "Número de Veces que se Usan los Comandos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(command_usage_total) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"bot:8080\", job=\"butakero-bot\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"butakero-bot\"} - go_memstats_frees_total{job=\"butakero-bot\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=\"bot:8080\", job=\"butakero-bot\"}[2m])"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=\"butakero-bot\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"bot:8080\", job=\"butakero-bot\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"butakero-bot\"}[2m])"
    }
   ]
  }
 ]
}