{
 "title": "Metricas cache bot",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Tasa de Fallos de Caché ",
   "type": "timeseries",
   "description": "Muestra la tasa de fallos en la caché a lo largo del tiempo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cache_misses_total{cache_type=\"metadata_cache\"}[1m]) / rate(cache_requests_total{cache_type=\"metadata_cache\"}[1m])",
     "legendFormat": "Fallos en caché {{ cache_type }}"
    },
    {
     "expr": "rate(cache_misses_total{cache_type=\"audio_cache\"}[1m]) / rate(cache_requests_total{cache_type=\"audio_cache\"}[1m])",
     "legendFormat": "Fallos en caché {{ cache_type }}"
    }
   ]
  },
  {
   "title": "Operaciones de Caché",
   "type": "timeseries",
   "description": "Muestra la cantidad de operaciones de caché (aciertos, fallos, eliminaciones, etc.) por período de tiempo.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(cache_hits_total[1m]))",
     "legendFormat": "Aciertos"
    },
    {
     "expr": "sum(rate(cache_misses_total[1m]))",
     "legendFormat": "Fallos"
    },
    {
     "expr": "sum(rate(cache_evictions_total[1m]))",
     "legendFormat": "Eliminaciones"
    },
    {
     "expr": "sum(rate(cache_requests_total[1m]))",
     "legendFormat": "Solicitudes"
    },
    {
     "expr": "sum(rate(cache_set_operations_total[1m]))",
     "legendFormat": "Establecimientos"
    },
    {
     "expr": "sum(rate(cache_get_operations_total[1m]))",
     "legendFormat": "Obtenciones"
    }
   ]
  },
  {
   "title": "Tamaño del Caché",
   "type": "timeseries",
   "description": "Muestra el tamaño del caché a lo largo del tiempo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "cache_size{job=\"butakero-bot\"}",
     "legendFormat": "Tamaño del Caché (MB)"
    }
   ]
  },
  {
   "title": "Tasa de Eliminaciones de Caché",
   "type": "timeseries",
   "description": "Muestra la tasa de eliminaciones de caché a lo largo del tiempo del audio.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(cache_misses_total{cache_type=\"audio_cache\"}[1m]) / rate(cache_requests_total{cache_type=\"audio_cache\"}[1m])",
     "legendFormat": "Tasa de Eliminaciones de Caché {{ cache_type }}"
    },
    {
     "expr": "rate(cache_misses_total{cache_type=\"metadata_cache\"}[1m]) / rate(cache_requests_total{cache_type=\"metadata_cache\"}[1m])",
     "legendFormat": "Tasa de Eliminaciones de Caché {{ cache_type }}"
    }
   ]
  },
  {
   "title": "Aciertos vs Fallos de Cache",
   "type": "timeseries",
   "description": "Muestra la cantidad de veces que se ha accedido a la caché correctamente (aciertos) versus la cantidad de veces que se ha necesitado ir a YouTube (fallos).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cache_hits_total{job=\"butakero-bot\", cache_type=\"audio_cache\"}",
     "legendFormat": "Aciertos en caché {{ cache_type }}"
    },
    {
     "expr": "cache_misses_total{job=\"butakero-bot\", cache_type=\"audio_cache\"}",
     "legendFormat": "Fallos en caché {{ cache_type }}"
    },
    {
     "expr": "cache_hits_total{job=\"butakero-bot\", cache_type=\"metadata_cache\"}",
     "legendFormat": "Aciertos en caché {{ cache_type }}"
    },
    {
     "expr": "cache_misses_total{job=\"butakero-bot\", cache_type=\"metadata_cache\"}",
     "legendFormat": "Fallos en caché {{  cache_type }}"
    }
   ]
  }
 ]
}