apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.sh: |
    #!/bin/bash
    
    until mongosh --eval "print('waiting...')" &>/dev/null; do
      sleep 2
    done

    mongosh --eval 'rs.initiate({
      _id: "rs0",
      members: [
        {_id: 0, host: "mongo-0.mongodb-service-cluster:27017"},
        {_id: 1, host: "mongo-1.mongodb-service-cluster:27017"},
        {_id: 2, host: "mongo-2.mongodb-service-cluster:27017"}
      ]
    })'

    sleep 10

    mongosh --eval 'admin = db.getSiblingDB("admin");
    admin.createUser({
      user: "root",
      pwd: "root",
      roles: [{ role: "root", db: "admin" }]
    });'