apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-kafka-user
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  template:
    secret:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "backend"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "backend"
  authorization:
    type: simple
    acls:
      # Permisos para los topics
      - resource:
          type: topic
          name: "bot.download.status"
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
          - Read
        host: "*"

      - resource:
          type: topic
          name: "bot.download.requests"
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
          - Read
        host: "*"

      # Permisos para operaciones administrativas
      - resource:
          type: cluster
          name: "kafka-cluster"
          patternType: literal
        operations:
          - Describe
        host: "*"
      
      # Permisos para grupos de consumo
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Read
        host: "*"