apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: my-mongodb
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "5.0.5"
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongodb-cert
      caCertificateSecretRef:
        name: mongodb-cert
      # optional: true
    authentication:
      modes:
      - SCRAM
  users:
  - name: admin-user
    db: admin
    passwordSecretRef:
      name: admin-user-password
    roles:
    - name: clusterAdmin
      db: admin
    - name: userAdminAnyDatabase
      db: admin
    - name: dbOwner  
      db: admin
    - name: clusterMonitor
      db: admin
    - name: read
      db: local
    - name: read
      db: admin
    - name: readAnyDatabase
      db: admin
    - name: hostManager
      db: admin
    - name: enableSharding
      db: admin
    - name: readWrite
      db: audio_service
    - name: dbOwner
      db: audio_service
    - name: dbAdmin
      db: audio_service
    scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongod
            resources:
              limits:
                cpu: "0.5"
                memory: 1Gi
              requests:
                cpu: 200m
                memory: 512Mi      
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - my-mongodb
                topologyKey: "kubernetes.io/hostname"
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 40G