FROM --platform=$BUILDPLATFORM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ cmd/
COPY internal/ internal/
ARG TARGETARCH
ARG TARGETOS
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="-s -w" -o main cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates ffmpeg python3 py3-pip curl \
    && python3 -m venv /venv \
    && /venv/bin/pip install --upgrade pip \
    && /venv/bin/pip install yt-dlp \
    && /venv/bin/pip install -U https://github.com/coletdjnz/yt-dlp-youtube-oauth2/archive/refs/heads/master.zip

WORKDIR /root/
COPY --from=builder /app/main .

ENV BUCKET_NAME=
ENV REGION=
ENV YOUTUBE_API_KEY=
ENV DYNAMODB_TABLE_NAME_SONGS=
ENV DYNAMODB_TABLE_NAME_OPERATION=
ENV SECRET_KEY=
ENV ACCESS_KEY=
ENV GIN_MODE=
ENV TOPIC=
ENV KAFKA_BROKERS=
ENV OAUTH2=
ENV ENV=
ENV DB_TYPE=
ENV STORAGE_TYPE=
ENV MESSAGING_TYPE=
ENV SQS_QUEUE_URL=
ENV BASE_PATH=

ENV PATH="/venv/bin:$PATH"

EXPOSE 8080
HEALTHCHECK CMD curl http://localhost:8080/api/health || exit 1

CMD ["./main"]