#!/bin/bash

BROWSER="chrome"                     # Cambia esto por el navegador que estas usando por ej firefox, brave, edge
COOKIES_FILE="cookies.txt"    
YT_COOKIES_FILE="yt-cookies.txt"


echo "Extrayendo cookies desde el navegador '$BROWSER'..."
yt-dlp --cookies-from-browser $BROWSER --cookies $COOKIES_FILE --skip-download https://www.youtube.com/watch?v=E2Rj2gQAyPA

if [[ $? -ne 0 || ! -f "$COOKIES_FILE" ]]; then
  echo "Error: No se pudieron extraer las cookies desde el navegador."
  exit 1
fi
echo "Cookies extraidas correctamente y guardadas en $COOKIES_FILE."

echo "# Netscape HTTP Cookie File" > "$YT_COOKIES_FILE"
echo "# This file is generated by yt-dlp. Do not edit." >> "$YT_COOKIES_FILE"

echo "Filtrando cookies relacionadas con '.youtube.com'..."
grep ".youtube.com" "$COOKIES_FILE" >> "$YT_COOKIES_FILE"

if [[ $? -ne 0 ]]; then
  echo "Error: No se encontraron cookies relacionadas con '.youtube.com'."
  exit 1
fi

rm -f "$COOKIES_FILE"

echo "Cookies relacionadas con '.youtube.com' guardadas en $YT_COOKIES_FILE."
