apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: backend
data:
  ENVIRONMENT: "local"
  GIN_MODE: "release"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "audio_service_db"
  MONGO_COLLECTION_SONGS: "songs"
  MONGO_COLLECTION_OPERATIONS: "operations"
  LOCAL_STORAGE_PATH: "/data/audio"
  KAFKA_TOPIC: "notification"
  OAUTH2: "false"
  COOKIES_YOUTUBE: "/configurations/yt-cookies.txt"
  SERVICE_MAX_ATTEMPTS: "5"
  SERVICE_TIMEOUT: "2"
  MONGO_HOST: "my-mongodb-0.my-mongodb-svc.mongodb.svc.cluster.local,my-mongodb-1.my-mongodb-svc.mongodb.svc.cluster.local,my-mongodb-2.my-mongodb-svc.mongodb.svc.cluster.local"
  KAFKA_CA_FILE: "/etc/kafka/ca-certs/ca.crt"
  KAFKA_CERT_FILE: "/etc/kafka/user-certs/user.crt"
  KAFKA_KEY_FILE: "/etc/kafka/user-certs/user.key"
  KAFKA_ENABLE_TLS: "true"
  KAFKA_BROKERS: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093"
  MONGO_CA_FILE: "/etc/mongodb/certs/ca.crt"
  MONGO_CERT_FILE: "/etc/mongodb/certs/tls.crt"
  MONGO_KEY_FILE: "/etc/mongodb/certs/tls.key"
  MONGO_ENABLE_TLS: "true"
  MONGO_REPLICA_SET_NAME: "my-mongodb"