apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-processing-audio
  namespace: backend
  labels:
    app: backend-processing-audio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-processing-audio
  template:
    metadata:
      labels:
        app: backend-processing-audio
    spec:
      containers:
      - name: backend-processing-audio
        image: tomasvilte/music-downloader-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GIN_MODE
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_PORT
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_DATABASE
        - name: MONGO_COLLECTION_SONGS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_COLLECTION_SONGS
        - name: MONGO_COLLECTION_OPERATIONS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_COLLECTION_OPERATIONS
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKERS
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_TOPIC
        - name: KAFKA_CA_FILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_CA_FILE
        - name: KAFKA_CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_CERT_FILE
        - name: KAFKA_KEY_FILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_KEY_FILE
        - name: KAFKA_ENABLE_TLS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_ENABLE_TLS
        - name: LOCAL_STORAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOCAL_STORAGE_PATH
        - name: MONGO_USER 
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_PASSWORD
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: YOUTUBE_API_KEY
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_HOST
        - name: MONGO_CA_FILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_CA_FILE
        - name: MONGO_CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_CERT_FILE
        - name: MONGO_KEY_FILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_KEY_FILE
        - name: MONGO_ENABLE_TLS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_ENABLE_TLS
        volumeMounts:
        - name: yt-cookies-volume
          mountPath: /root/configurations/yt-cookies.txt
          subPath: yt-cookies.txt
        - name: kafka-user-cert
          mountPath: /etc/kafka/user-certs
          readOnly: true
        - name: kafka-ca-cert
          mountPath: /etc/kafka/ca-certs
          readOnly: true
        - name: mongodb-cert
          mountPath: /etc/mongodb/certs
          readOnly: true
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: yt-cookies-volume
        secret:
          secretName: backend-secret
          items:
          - key: YT_COOKIES
            path: yt-cookies.txt
      - name: kafka-user-cert
        secret:
          secretName: my-kafka-user
          items:
          - key: user.crt
            path: user.crt
          - key: user.key
            path: user.key
      - name: kafka-ca-cert
        secret:
          secretName: kafka-server-cert
          items:
          - key: ca.crt
            path: ca.crt
      - name: mongodb-cert
        secret:
          secretName: mongodb-cert
          items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key