apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-files-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard