apiVersion: v1
kind: Service
metadata:
  name: audio-processing-service
  namespace: backend
spec:
  selector:
    app: audio-processing-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP